# Site Configuration
title: "AI Insights Hub"
description: "Your premier destination for cutting-edge AI insights, research, and practical applications in artificial intelligence."
url: "https://aiinsightshub.com"
baseurl: ""
language: "en"
author: "AI Insights Hub Team"
timezone: "UTC"

# SEO Configuration
seo:
  title: "AI Insights Hub - Cutting-Edge AI Research & Insights"
  description: "Your premier destination for cutting-edge AI insights, research, and practical applications in artificial intelligence."
  keywords: ["artificial intelligence", "machine learning", "deep learning", "AI research", "AI tools", "computer vision", "natural language processing", "AI ethics"]
  author: "AI Insights Hub Team"
  image: "/assets/images/ai-insights-hub.jpg"

# Social Media
social:
  twitter: "https://twitter.com/AIInsightsHub"
  linkedin: "https://linkedin.com/company/aiinsightshub"
  github: "https://github.com/AIInsightsHub"
  youtube: "https://youtube.com/@AIInsightsHub"

# Contact Information
contact:
  email: "hello@aiinsightshub.com"
  twitter: "@AIInsightsHub"
  github: "AIInsightsHub"

# AI Categories
ai_categories:
  - name: "Machine Learning"
    description: "Algorithms, techniques, and practical applications"
  - name: "Deep Learning"
    description: "Neural networks and advanced architectures"
  - name: "AI Applications"
    description: "Real-world implementations and case studies"
  - name: "AI Research"
    description: "Latest breakthroughs and developments"
  - name: "AI Ethics"
    description: "Responsible AI development and governance"
  - name: "AI Tools"
    description: "Development platforms and resources"
  - name: "Data Science"
    description: "Data preprocessing and analysis for AI"
  - name: "Computer Vision"
    description: "Image recognition and visual AI"

# Google Analytics
google_analytics_id: "G-XXXXXXXXXX"
google_site_verification: "your_verification_code"

# Automation Configuration
automation:
  niche: "artificial intelligence"
  country: "united_states"
  language: "en"
  min_word_count: 1500
  max_word_count: 2500
  generation_backend: "template"  # Options: template, openai, hf_api
  internal_links_max: 3
  backup_keywords_file: "scripts/backup_keywords.txt"

# Build Settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - scripts/
  - .automation/
  - README.md
  - LICENSE
