# Site settings
title: "Niche Daily"
description: "Daily insights on trending topics in your chosen niche."
url: "https://shoaibkhan191.github.io"
baseurl: "/nichedaily"
language: "en-US"
permalink: "/:title/"

# SEO settings
seo:
  title: "Niche Daily - Your Source for Trending Niche Topics"
  description: "Stay ahead with daily SEO-optimized articles on trending topics in your chosen niche."
  keywords: "trending topics, daily blog, SEO blog, niche news, latest updates"
  author: "Niche Daily Team"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

# Feed settings
feed:
  path: feed.xml

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Social links (optional)
social:
  twitter: "https://twitter.com/YourProfile"
  facebook: "https://facebook.com/YourProfile"
  instagram: "https://instagram.com/YourProfile"
  linkedin: "https://linkedin.com/in/YourProfile"

# Google Analytics (optional)
# Use GA4 ID here; layouts read `google_analytics_id`
google_analytics_id: "G-XXXXXXXXXX" # Replace with your tracking ID

# Google Search Console (optional)
google_site_verification: "" # Add verification token

# Adsense (optional)
adsense:
  publisher_id: "pub-xxxxxxxxxxxxxxxx" # Replace with your Adsense Publisher ID

# Exclude unnecessary files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
